#!/bin/sh
set -e

perl -le 'printf "MPD_SECRETWORD=";print map { ("a".."z","A".."Z")[rand 52] } 1..40' > $HOME/.mpd.conf
chmod 600 $HOME/.mpd.conf

wget --no-check-certificate https://github.com/gridaphobe/CRL/raw/master/GetComponents
chmod +x GetComponents
./GetComponents -p -a http://svn.einsteintoolkit.org/manifest/trunk/einsteintoolkit.th
mkdir simulations
cd Cactus
./simfactory/bin/sim setup-silent --optionlist=debian.cfg
set +e
./simfactory/bin/sim build --thornlist=./thornlists/einsteintoolkit.th
set -e
make sim
./simfactory/bin/sim create-run tests_1 --testsuite --procs 1
#./simfactory/bin/sim create-run tests_2 --testsuite --procs 2

