#!/bin/bash
set -e

perl -le 'printf "MPD_SECRETWORD=";print map { ("a".."z","A".."Z")[rand 52] } 1..40' > $HOME/.mpd.conf
chmod 600 $HOME/.mpd.conf

RELEASE=ET_2013_11
wget --no-check-certificate https://github.com/gridaphobe/CRL/raw/$RELEASE/GetComponents
chmod +x GetComponents
./GetComponents -p -a http://svn.einsteintoolkit.org/manifest/branches/$RELEASE/einsteintoolkit.th
cd Cactus
./simfactory/bin/sim setup-silent --optionlist=debian.cfg --ppn=8
mkdir -p ~/simulations
set +e
time ./simfactory/bin/sim build --thornlist=./thornlists/einsteintoolkit.th 2>&1 | tee ET_build.log
set -e
make sim
./simfactory/bin/sim create-run tests_1 --testsuite --procs 1
./simfactory/bin/sim create-run tests_2 --testsuite --procs 2

