#!/bin/bash
RELEASE=$1
if [ ! -f install_$RELEASE ] ; then
  echo "You need to specify a release and the file install_\$RELEASE needs to be present.";
  exit 1
fi
VBoxManage storageattach $RELEASE --storagectl "IDE Controller" --port 0 --device 0 --type dvddrive --medium none
VBoxManage storageattach $RELEASE --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium none
VBoxManage closemedium dvd ~/vm/$RELEASE.iso
VBoxManage closemedium disk --delete HardDisks/$RELEASE.vdi
VBoxManage unregistervm $RELEASE --delete
